apiVersion: v1
kind: Service
metadata:
  name: app-users
  labels:
    app: app-users
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: app-users
