apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-users
  labels:
    app: app-users
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-users
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: app-users
    spec:
      containers:
        - name: app-users
          image: rapp/appusers:1.0
          env:
            - name: JAVA_OPTS
              value: "-Djava.net.preferIPv4Stack=true"
            - name: JAVA_AGENT_OPTS
              value: "--add-modules java.se --add-exports java.base/jdk.internal.ref=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens java.management/sun.management=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED"
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: sys-app-credentials
                  key: MYSQL_USER
                  optional: false
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sys-app-credentials
                  key: MYSQL_PASSWORD
                  optional: false
            - name: MYSQL_HOST
              value: "10.96.5.143"
            - name: MYSQL_PORT
              value: "3306"
            - name: MYSQL_DATABASE
              value: "db_users"
          ports:
            - containerPort: 8080
              name: rest
              protocol: TCP
